name: football_app
description: A new Flutter project.
publish_to: "none"

version: 2.0.56+56

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  ionicons: ^0.2.2
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  animate_do: ^3.0.2
  video_player: ^2.6.1
  flutter_widget_from_html_core: ^0.10.1
  url_launcher: ^6.1.12
  google_fonts: ^4.0.4
  sizer: ^2.0.15
  get: ^4.6.5
  email_validator: ^2.1.17
  firebase_core: ^2.24.2
  provider: ^6.0.5
  dio: ^5.3.2
  rx_shared_preferences: ^3.0.0
  file_picker: ^5.3.3
  flutter_svg: ^2.0.7
  flutter_speed_dial: ^7.0.0
  real_volume: ^1.0.6
  collection: ^1.17.1
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  flutter_login_facebook: ^1.8.0
  custom_navigation_bar: ^0.8.2
  easy_localization: ^3.0.3
  in_app_purchase: ^3.1.11
  pretty_dio_logger: ^1.3.1
  quiver: ^3.2.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2
  intl: ^0.18.0
  pull_to_refresh: ^2.0.0
  elliptic_text: ^1.0.1+9
  flutter_countdown_timer: ^4.1.0
  fluttertoast: ^8.2.4
  showcaseview: ^2.0.3
  share_plus: ^7.2.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  uni_links: ^0.5.1
  loading_indicator: ^3.1.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/league/
    - assets/images/tiktok/
    - assets/video/
    - assets/lang/
    - assets/sounds/

  fonts:
    - family: Aero
      fonts:
        - asset: assets/fonts/Aero.ttf
    - family: Algerian
      fonts:
        - asset: assets/fonts/Alexandria Regular.ttf
    - family: DELIRIUM
      fonts:
        - asset: assets/fonts/FTY DELIRIUM NCV.otf
