// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyf1G9luSJ3zNia-PUQJb7gBLJV8no2A',
    appId: '1:1004845702880:android:5d0578543187a864803a85',
    messagingSenderId: '1004845702880',
    projectId: 'footballapp-ea132',
    storageBucket: 'footballapp-ea132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNqDnlK7ADGuPO4EMyV59uNL5QCBzvUc',
    appId: '1:1004845702880:ios:2d32401cae78b952803a85',
    messagingSenderId: '1004845702880',
    projectId: 'footballapp-ea132',
    storageBucket: 'footballapp-ea132.appspot.com',
    androidClientId: '1004845702880-0gpi821i47ra1tq16gi223l3d6g8c5b3.apps.googleusercontent.com',
    iosClientId: '1004845702880-2hn3q6fmv9c7f3urbn98efqleuavk65j.apps.googleusercontent.com',
    iosBundleId: 'com.fel.sports.app',
  );
}
